### ISSUE TITLE
Notify the Analytics application each time an application icon is pressed [2-4h]

### ISSUE THREAD

**Issue by literacyapp** [literacyapp-org/android_packages_apps_Trebuchet_Gradle#10]
Implement usage of `EventTracker.reportApplicationOpenedEvent`

For information on how to import the Event Tracker Gradle library, see https://github.com/literacyapp-org/literacyapp-android/commit/aa78a1f6a416e447cfd75f3760aa21505b17e9c0

**Comment by jogrimst** [comment]
@bojanvu23 Did you find the Launcher method where the application icon clicks are handled?

**Comment by jogrimst** [comment]
@bojanvu23 Is there any way to detect if the icon press happens on the home screen or in the drawer?

**Comment by bojanvu23** [comment]
@jogrimst 

Yes, there isn't problem to be done, I only need tracking string for each action.

**Comment by bojanvu23** [comment]
@jogrimst 

Currently there is method:
EventTracker.reportApplicationOpenedEvent(Context context, String packageName);
which is used for both app's icon press(home-screen and drawer).
So there is need for new method or for adding flag to existing. 

Adding this into Launcher app will take half hour.
