### ISSUE TITLE
Fix duplicate permission error

### ISSUE THREAD

**Issue by literacyapp** [literacyapp-org/android_packages_apps_Trebuchet_Gradle#2]
Installation of APK file fails: `Failure [INSTALL_FAILED_DUPLICATE_PERMISSION perm=com.android.launcher3.permission.RECEIVE_FIRST_LOAD_BROADCAST pkg=com.cyanogenmod.trebuchet]`

**Comment by bojanvu23** [comment]
The fix is done, and it works.
closing the issue.

**Comment by bojanvu23** [comment]
This is fixed, closing ticket.
